apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buggy-web-app
  template:
    metadata:
      labels:
        app: buggy-web-app
    spec:
      containers:
      - name: buggy-web-app
        image: 975050199901.dkr.ecr.us-east-1.amazonaws.com/buggy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: buggy-web-app
    k8s-app: buggy-web-app
  name: buggy-web-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: buggy-web-app
